export const FETCH_TRENDING = "FETCH_TRENDING";
export const FETCH_NETFLIX_ORIGINALS = "FETCH_NETFLIX_ORIGINALS";
export const FETCH_TOP_RATED = "FETCH_TOP_RATED";
export const FETCH_ACTION_MOVIES = "FETCH_ACTION_MOVIES";
export const FETCH_COMEDY_MOVIES = "FETCH_COMEDY_MOVIES";
export const FETCH_HORROR_MOVIES = "FETCH_HORROR_MOVIES";
export const FETCH_ROMANCE_MOVIES = "FETCH_ROMANCE_MOVIES";
export const FETCH_DOCUMENTARIES = "FETCH_DOCUMENTARIES";
